### ISSUE TITLE
[Bug] Console spammed by OpenGl debugging message

### ISSUE THREAD

**Issue by DisappointingToaster** [LodestarMC/Lodestone#33] opened 2024-06-23 09:30 UTC
Hi,
Currently experiencing an issue with latest version of Lodestone. 
In presence of [Immersive Engineering ](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering), console and latest log keeps repeatedly getting spammed "[mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'"
Removing either of the mods causes the issue to stop.

![prismlauncher_hf1hMkTvuH](https://github.com/LodestarMC/Lodestone/assets/29438422/0c152974-449b-442e-a829-1610bc6df239)

Using Lodestone version 1.6.1, Immersive Engineering 10.1.0-171, NeoForge 47.1.106
Attaching latest log file from forge:
[latest.log](https://github.com/user-attachments/files/15944007/latest.log)

**Comment by oliverrook** [comment] 2024-07-03 15:31
Same. Causes severe lag, actually.

**Comment by ambientNexus** [comment] 2024-07-04 08:13
Same issue here. Really hoping this gets fixed soon, no idea why we haven't gotten any updates on this issue as of yet.

**Comment by Atlas-Maker** [comment] 2024-07-26 04:57
also having this problem it's really not fun
anyway you can do a quick fix by disabling the stencil buffer in immersive engineering

**Comment by vertexcubed** [comment] 2024-08-11 00:46
This error also occurs with Timeless and Classic Zero.

**Comment by Mechanax** [comment] 2024-08-11 04:36
I found a more detailed message in the launcher's log file that might help a bit.
https://pastebin.com/Wt9DNbCA

**Comment by mrsterner** [comment] 2024-08-11 13:37
Fixed by disabling Immersive Engineering's Stencil buffer config

**Comment by HypnoticChris** [comment] 2024-09-10 04:52
Disabling the Stencil buffer config did not fix it for me, but it is definitely a lodestone issue, I have multiple log files that are like 400mb in size, and they are literally text files, I really want to use malum in my modpack since it is such a cool mod that I have never used before, but I can't keep lodestone in the modpack if it will cause so much performance issues

**Comment by PinkDisorder** [comment] 2024-09-10 11:08
this happens with gregtech community modern as well https://github.com/GregTechCEu/GregTech-Modern/issues/1536

**Comment by ambientNexus** [comment] 2024-09-10 23:18
Jeez, this has been an issue approaching on 3 months now, and even worse it's an issue with multiple mods?

**Comment by SammySemicolon** [comment] 2024-09-10 23:24
It's hard to really say what causes this in particular, so

**Comment by PinkDisorder** [comment] 2024-09-11 00:05
is there any kind of further data we as users could provide to help debug this?

**Comment by vertexcubed** [comment] 2024-09-11 03:43
Does Lodestone make any changes to the stencil buffer? that's the only thing I could think of causing an issue like this

**Comment by Its-Cryptic** [comment] 2024-09-11 05:09
Nope, ive narrowed down the issue to the LODEDSTONE_DEPTH_CACHE inside RenderHandler. Ill try to get that fixed asap

**Comment by ambientNexus** [comment] 2024-09-11 05:23
Thank you so much for figuring out the cause.

**Comment by Its-Cryptic** [comment] 2024-09-11 05:35
Fixed in Lodestone [1.20.1-1.6.2.3.227](https://maven.blamejared.com/team/lodestar/lodestone/lodestone/1.20.1-1.6.2.3.227/)

**Closed by Its-Cryptic** 2024-09-11 05:35 UTC
